language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jetfire' ]; then cd .. && eval "mv $currentfolder generator-jetfire" && cd generator-jetfire; fi

